### ISSUE TITLE
Add support for Bootstrap v3

### ISSUE THREAD

**Issue by peritus** [noizwaves/bootstrap-social-buttons#4]
Could you make this very awesome project compatible w/ bootstrap 3 ? :heart: 

http://blog.getbootstrap.com/2013/07/27/bootstrap-3-rc1/

**Comment by noizwaves** [comment]
Hi Filip,

Glad to hear you like the project :) Bootstrap 3 support is definitely on the radar, and now 3 is getting close to release this will become an important version for us to support.

I'll try and carve out a few hours to work on this over the weekend; unless you have some time and want to submit a pull request... :)

**Comment by noizwaves** [comment]
Ok, initial Bootstrap 3 support has been pushed. It's online at http://noizwaves.github.io/bootstrap-social-buttons/3/ and I'd love your feedback/thoughts. I haven't worked with Flat UI yet, so I'm not sure what the 'rules' are.

**Comment by noizwaves** [comment]
Bootstrap 3 support now complete! Check out v1.0.0 for more details.

**Comment by mapb1990** [comment]
I'm forked this repo and follow another approach for twitter bootstrap 3. 
https://github.com/mapb1990/bootstrap-social-buttons
