### ISSUE TITLE
Buttons not visible on ubuntu Chrome.

### ISSUE THREAD

**Issue by irla** [noizwaves/bootstrap-social-buttons#5]
HI, 
really nice buttons.
I wonder why they are not displying correctly on google chrome Version 29.0.1547.65, Operating system Ubuntu 13.04 - Works perfectly on Firefox.

Screenshot attached:
![image](https://f.cloud.github.com/assets/1569392/1162676/37c39f6a-2023-11e3-9749-24518d1e73ef.png)

**Comment by noizwaves** [comment]
Thanks for reporting this! I don't have a local 13.04 machine setup right now, but I'll spin one up soon and try to replicate.

I was unable to replicate this in Chrome on a 12.04.2 Ubuntu machine.

**Comment by irla** [comment]
I just checked it again. My chrome updated to version 29.0.1547.76 - now main page of social buttons looks like this:

![image](https://f.cloud.github.com/assets/1569392/1197591/f1f5ee2c-24df-11e3-8a0a-3230da9d0d67.png)

Looks like very specific configuration problem. Maybe we should wait for next chrome update...

**Comment by noizwaves** [comment]
Very strange indeed. I'm suspicious about the missing Facebook and Twitter example buttons. Are you able inspect the DOM to see where they've gone?

![screen shot 2013-09-24 at 4 12 23 pm](https://f.cloud.github.com/assets/1007983/1197606/609f1182-24e0-11e3-95e1-accdcc7e9fdd.png)

**Comment by irla** [comment]
Looks like bug in Chrome to me.
![image](https://f.cloud.github.com/assets/1569392/1197635/176776c0-24e1-11e3-8cd4-964128da04ed.png)

**Comment by noizwaves** [comment]
Intriguing. I'll see what I can find out.

**Comment by irla** [comment]
What can be interesting. Chrome css says it has display set to 'none'.

![image](https://f.cloud.github.com/assets/1569392/1197682/13a60d52-24e2-11e3-90e5-0a9a519844d9.png)

I think we can wait for next Chrome releases and see what will happened. They improved how page is displayed between 29.0.1547.65 and 29.0.1547.76 ;)

**Comment by Belar** [comment]
Encountered the same error with Facebook and Twitter buttons and diagnosed possible naming collision. Funny thing only these 2 buttons were affected. 

When changed "facebook" to "fb" and "twitter" to "twr" in CSS (social-buttons-3.css), style is loaded correctly for:
`<button class="btn btn-fb"><i class="icon-facebook"></i> | Connect with Facebook</button>`
`<button class="btn btn-twr"><i class="icon-twitter"></i> | Connect with Twitter</button>`
 Name change in font-awesome would probably fix icons.

Solution: Turn off AdBlock Plus :D

**Comment by noizwaves** [comment]
Haha, this oddly makes sense!

Just build a fresh Ubuntu 13.04 machine with full updates and latest Chrome, and the buttons are all visible this end. 

Once Adblock Plus is installed and the 'Remove Social Media Buttons' option is enabled, the buttons disappear on page refresh.

I imagine some Adblock users would consider these buttons to be comparable Facebook and Twitter buttons, and thus want them blocked; so respecting Adblock's rules makes sense. On the other hand, having these key buttons removed by the extension seriously breaks the UX of websites developed with Social Buttons.

**Comment by irla** [comment]
Ha, simple and great solution.

I even didn't remember I have blocked it. Anyway I will not unblock it - I really don't like this facebook contents on web pages. I think there are couple nerds on the world which also blocks it - so I will just change the class names on page where I will use it.

Thank you very much - great job!

**Comment by Belar** [comment]
Yeah, class change does the trick. Adblock users will have to deal with no icons version of a button. Bug busted tho :D.

**Comment by noizwaves** [comment]
Cause of missing styles identified. Closing this bug.
