### ISSUE TITLE
Font Embed code

### ISSUE THREAD

**Issue by audas** [noizwaves/bootstrap-social-buttons#7]
It has change from icon-facebook to fa fa-facebook

This was confusing for a little while - would be good to update it for new users.

**Comment by metude** [comment]
Thank you very much audas. I was looking for what causes to the problem.

**Comment by noizwaves** [comment]
Great suggestion, I'll update the docs to reflect this.

**Comment by noizwaves** [comment]
The docs and sample pages have now been updated. Thank you for reporting this!

**Comment by audas** [comment]
Derp.

Glad to help in some small way.
