### ISSUE TITLE
Email icon?

### ISSUE THREAD

**Issue by karan** [noizwaves/bootstrap-social-buttons#8]
Is it possible to get the email icon?

**Comment by noizwaves** [comment]
Hi Karan, sorry about the late reply! Email is definitely possible using Font Awesome's fa-envelope and fa-envelope-o icons. As for the button style, I'm not sure there is a 'standard' colour for such a button.

If you come up with a good style, I'd be happy to include it in this project.

**Comment by karan** [comment]
It wasn't hard to get it to work:

Jade:
https://github.com/karan/goel.im/blob/master/index.jade#L238-L240

Html:
https://github.com/karan/goel.im/blob/master/index.html#L152

```
<div class="col-md-1"><a href="mailto:karan@goel.im" role="button" class="btn btn-vk btn-xlarge"><i class="fa fa-envelope-o"></i></a></div>
```

**Comment by noizwaves** [comment]
Thanks for the update.
